# Generated by Django 3.2.6 on 2021-10-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0002_community_project_projectdescription_projectimages_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
    ]
