# Generated by Django 3.2.6 on 2021-09-30 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INTERVIEW', 'INTERVIEW'), ('PROJECT', 'PROJECT')], max_length=100, null=True)),
                ('itemId', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('added_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('postfolio', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('about_me', models.CharField(max_length=1000, null=True)),
                ('college', models.JSONField(default=dict)),
                ('internships', models.JSONField(default=dict)),
                ('company', models.JSONField(default=dict)),
                ('dob', models.DateField(null=True)),
                ('communities', models.JSONField(default=list)),
                ('following_cnt', models.IntegerField(default=0)),
                ('followers_cnt', models.IntegerField(default=0)),
                ('following', models.JSONField(default=list)),
                ('followers', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('creation_time', models.TimeField()),
                ('type', models.CharField(choices=[('FOLLOWING', 'FOLLOWING'), ('COMMENT', 'COMMENT'), ('TAG', 'TAG'), ('PROFILE VIEW', 'PROFILW VIEW'), ('PROJECT VIEW', 'PROJECT VIEW')], max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('VIEWED', 'VIEWED')], max_length=200, null=True)),
                ('creator', models.CharField(max_length=100, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.userprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
