# Generated by Django 3.2.6 on 2021-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('FOLLOWING', 'FOLLOWING'), ('COMMENT', 'COMMENT'), ('TAG', 'TAG'), ('PROFILE VIEW', 'PROFILE VIEW')], max_length=100, null=True),
        ),
    ]
